---
title: "Laszlo Szabo's CV"
author:
  firstname: Laszlo
  lastname: Szabo
  address: "Cardiff and Vale University HB, Cardiff, UK"
  position: Consultant Transplant Surgeon
  contacts:
    - icon: fa envelope
      text: Laszlo.Szabo@wales.nhs.uk
      url: "mailto:Laszlo.Szabo@wales.nhs.uk"
    - icon: fa brands orcid
      text: 0000-0002-6881-1542
      url: https://orcid.org/0000-0002-6881-1542
    - icon: fa brands github
      text: Laszlo75
      url: https://github.com/Laszlo75
    - icon: fa brands linkedin
      text: drszabolaszlo
      url: https://linkedin.com/in/drszabolaszlo
    # - icon: fa brands x-twitter
    #   text: twitter
    #   url: https://twitter.com/example
style:
   color-accent: "005EB8"
   font-header: "SF Pro Text"
   font-text: "SF Pro Text"
format: awesomecv-typst

execute:
  echo: false
  warning: false
  message: false
---

```{r}
#| label: load package
# install.packages("typstcv", repos = "https://kazuyanagimoto.r-universe.dev")
library(typstcv)
```

## Education

```{r}
#| label: education
#| output: asis

education <- data.frame(
  title = c("Medical Doctor", "Specialist in Surgery (CCT equivalent)"),
  location = c("Debrecen, Hungary", "Debrecen, Hungary"),
  start = as.Date(c("1993-01-01", "1999-01-01")),
  end = as.Date(c("1999-01-01", "2006-01-01")),
  # date = c("1999", "2006"),
  description = c(
    "Medical and Health Science Centre, University of Debrecen, Hungary",
    "Hungarian National Board of Surgery"
  )
)

# write.csv(education, "assets/data/education.csv", row.names = FALSE)

education |>
  format_date(end = "end", date_format = "%Y", sort_by = "end") |>
  resume_entry()

```

## Qualifications

```{r}
#| label: qualifications
#| output: asis

qualifications <- data.frame(
  title = c(
    "European Diploma in Transplantation Surgery",
    "European Diploma in Transplantation Surgery"
  ),
  location = c(
    "Brussels",
    "Paris"
  ),
  date = c("2015", "2009"),
  description = c(
    "European Board of Surgery, Division of Transplantation",
    "European Board of Surgery, Division of Transplantation"
  )
)

# Here's how to add the detail column with the specified items:

qualifications <- data.frame(
  title = c(
    "European Diploma in Transplantation Surgery",
    "European Diploma in Transplantation Surgery"
  ),
  location = c(
    "Brussels",
    "Paris"
  ),
  date = c("2015", "2009"),
  description = c(
    "European Board of Surgery, Division of Transplantation",
    "European Board of Surgery, Division of Transplantation"
  ),
  detail = c(
    "Module 3: Pancreas Transplantation",
    "Module 1: Multiorgan retrieval\n- Module 2: Kidney Transplantation"
  )
)


qualifications |>
  resume_entry(details = "detail")

```

## Work Experience

```{r}
#| label: work experience
#| output: asis

work <- data.frame(
  title = c(
    "Consultant Transplant Surgeon",
    "Clinical Fellow in Transplant Surgery and Organ Retrieval",
    "Surgeon, Assistant Lecturer",
    "Surgical Trainee"
  ),
  location = c(
    "Cardiff, UK",
    "Cardiff, UK",
    "Debrecen, Hungary",
    "Debrecen, Hungary"
  ),
  start = as.Date(c(
    "2012-09-17",
    "2011-01-01",
    "2006-01-01",
    "1999-10-01"
  )),
  end = as.Date(c(
    "",
    "2012-09-16",
    "2011-01-01",
    "2006-01-01"
  )),
  # date = c("2018 - present", "2006 - 2018"),
  description = c(
    "Cardiff Transplant Unit, Cardiff and Vale University Health Board",
    "Cardiff Transplant Unit, Cardiff and Vale University Health Board",
    "Institute of Surgery, Medical and Health Science Centre, University of Debrecen",
    "Institute of Surgery, Medical and Health Science Centre, University of Debrecen"
  )
)
work |>
  format_date(end = "end", date_format = "%Y", sort_by = "start") |>
  resume_entry()
```

## Leadership Roles

```{r}
#| label: roles
#| output: asis

roles <- data.frame(
  title = c(
    "Transplant and Vascular Access Lead with the Welsh Kidney Network",
    "Clinical Lead for Governance",
    "Clinical Lead for Organ Utilisation"
  ),
  date = c(
    "2024 - present",
    "2021 - present",
    "2020 - present"
  )
)

resume_entry(roles)

```

\newpage

## Research

**Principal Investigator**

```{r}
#| label: research
#| output: asis

research_pi <- data.frame(
  title = c(
    "PITHIA",
    "POWAR",
    "COPE-COMPARE",
    "COPE-POMP",
    "PAVE"
  ),
  description = c(
    "Pre-implantation Trial of Histopathology In renal Allografts",
    "Prophylaxis of Wound Infections - Antibiotics in Renal Donation",
    "Oxygenated versus standard cold perfusion preservation in  kidney transplantation",
    "'in house' pre-implantation oxygenated hypothermic machine perfusion reconditioning after cold storage versus cold storage alone in expanded criteria donor (ECD) kidneys from brain dead donors",
    "Paclitaxel-assisted balloon angioplasty of venous stenosis in haemodialysis access"
  )
)

resume_entry(research_pi)

```

## Skills

```{r}
#| label: skills
#| output: asis

skill <- data.frame(
  title = c("Surgical Skills", "Languages", "Data Science"),
  description = c(
    "kidney and pancreas transplantation, organ retrieval, normothermic regional perfusion, vascular access",
    "Hungarian (native), English (fluent), French (basic)",
    "R, RStudio, Quarto, Typst, Power BI"
  )
)
resume_entry(skill)

# skill
```

\newpage

```{=typst}
#bibliography("assets/my-publication-list.bib", title: "Publications", full: true)
```
